//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidoServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string nickName { get; set; }
        public string passcode { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
    }
}
